name: 'Set up Docker'
description: 'Pulls docker image from registry, or builds if not available'
runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Compute Dockerfile hash
      id: dockerfile-hash
      shell: bash
      run: |
        HASH=$(sha256sum docker/${{ inputs.dockerfile }} | cut -d' ' -f1 | cut -c1-12)
        echo "hash=$HASH" >> $GITHUB_OUTPUT
        echo "Dockerfile hash: $HASH"

    - name: Convert owner to lowercase
      id: repo
      shell: bash
      run: |
        echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Try to pull Docker image from registry
      id: pull
      shell: bash
      continue-on-error: true
      run: |
        set -xe
        docker pull ghcr.io/${{ steps.repo.outputs.owner }}/navtoolkit:${{ inputs.tag }}-${{ steps.dockerfile-hash.outputs.hash }}

    - name: Set up Docker Buildx
      if: steps.pull.outcome == 'failure'
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      if: steps.pull.outcome == 'failure'
      id: docker_build
      uses: docker/build-push-action@v5
      with:
          context: docker/
          file: docker/${{ inputs.dockerfile }}
          push: true
          tags: ghcr.io/${{ steps.repo.outputs.owner }}/navtoolkit:${{ inputs.tag }}-${{ steps.dockerfile-hash.outputs.hash }}
      env:
        SOURCE_DATE_EPOCH: 0

    - name: Retag image
      shell: bash
      run: docker tag ghcr.io/${{ steps.repo.outputs.owner }}/navtoolkit:${{ inputs.tag }}-${{ steps.dockerfile-hash.outputs.hash }} navtoolkit-${{ inputs.tag }}

    - name: Create iidfile
      shell: bash
      run: |
          set -xe
          mkdir -p docker/build/iidfiles/
          echo navtoolkit-${{ inputs.tag }} > docker/build/iidfiles/${{ inputs.platform }}

    - name: Ensure ccache directory exists
      shell: bash
      run: mkdir -p ~/.ccache

inputs:
  platform:
    description: 'Docker image name'
    required: false
    default: ubuntu-noble
  dockerfile:
    description: 'Dockerfile filename'
    required: false
    default: Dockerfile.ubuntu
  tag:
    description: 'Docker image tag'
    required: false
    default: ubuntu-noble