[build-system]
# Build dependencies
requires = [
    'aspn23_xtensor==1.0.0',
    'meson-python',
    'meson==1.8.4',
    'numpy',
    'pybind11-stubgen>=2.5.5',
    'cxxheaderparser==1.8.1',
]
build-backend = 'mesonpy'

[tool.ruff]
line-length=79
required-version = '>=0.15.16'

[tool.ruff.lint]
preview = true
select = ['E', 'F', 'I', 'W']
ignore = [
    'E741',  # Ignores error from math-variables, like 'I'.
]
isort.split-on-trailing-comma=false

[tool.ruff.format]
quote-style='single'
skip-magic-trailing-comma = true

[tool.meson-python.args]
setup = [
    '-Dbuild_docs_tests_examples=false',
    '-Dmain_library=false',
    '-Dpython_bindings=true',
    '-Dgdal_extensions=disabled',
    '-Dget_navtk_data=true',
    '-Daspn-generated:aspn-cpp=disabled',
    '-Daspn-generated:aspn-c=disabled',
]
install = ['--tags=runtime,python-runtime']

[project]
# Runtime dependencies
dependencies = ['aspn23_xtensor==1.0.0', 'numpy']
name = 'navtk'
dynamic = ['version']
description = 'NavToolkit Python Bindings'
license = 'Apache-2.0'
license-files = ['LICENSE']
readme = 'README_PYTHON_PACKAGE.md'

[tool.cibuildwheel]
environment = { PIP_INDEX_URL = "https://test.pypi.org/simple/", PIP_EXTRA_INDEX_URL = "https://pypi.org/simple/" }

[tool.cibuildwheel.linux]
before-all = "yum install openblas-devel -y"

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel pkgconf && bash {project}/util/cibw_prepare_windows.sh {project}"
repair-wheel-command = "delvewheel repair --add-path .openblas/bin --include msvcp140.dll -w {dest_dir} {wheel}"
config-settings = { setup-args = ["--vsenv"] }

[[tool.cibuildwheel.overrides]]
select = "*armv7*"
before-all = """
  apt-get update &&
  apt-get install -y libopenblas-dev gcc-10 g++-10 &&
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 &&
  update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 60
"""

[tool.pytest.ini_options]
norecursedirs = ["subprojects"]

[dependency-groups]
dev = [
    'ruff>=0.15.16',
]
