#pragma once

#include <memory>
#include <string>

#include <navtk/aspn.hpp>
#include <navtk/filtering/processors/MeasurementProcessor.hpp>
#include <navtk/not_null.hpp>

namespace navtk {
namespace filtering {

/**
 * Processes Measurements containing an `MeasurementAttitude3D` to update whole-valued roll, pitch,
 * yaw states, or a `filtering::PairedPva` wrapping a `MeasurementAttitude3D` to update NED tilt
 * error states. See generate_model() for details.
 */
class Attitude3dMeasurementProcessor : public MeasurementProcessor<> {

public:
	/**
	 * Constructor for processor that updates only one state block.
	 *
	 * @param label Name of this processor.
	 * @param state_block_label A label referring to the StateBlock this processor updates. How
	 * updates are performed depends on the number of states in the block and the type of
	 * measurement received; see generate_model().
	 * @param expected_frame Logs a warning when the ASPN measurement's reference frame differs from
	 * \p expected_frame
	 */
	Attitude3dMeasurementProcessor(std::string label,
	                               const std::string& state_block_label,
	                               AspnMeasurementAttitude3DReferenceFrame expected_frame =
	                                   ASPN_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_NED);

	/**
	 * Constructor for processor that updates multiple state blocks.
	 *
	 * @param label Name of this processor.
	 * @param state_block_labels A group of labels referring to the StateBlocks this processor
	 * updates. How updates are performed depends on the number of states in the blocks and the type
	 * of measurement received; see generate_model().
	 * @param expected_frame Logs a warning when the ASPN measurement's reference frame differs from
	 * \p expected_frame
	 */
	Attitude3dMeasurementProcessor(std::string label,
	                               std::vector<std::string> state_block_labels,
	                               AspnMeasurementAttitude3DReferenceFrame expected_frame =
	                                   ASPN_MEASUREMENT_ATTITUDE_3D_REFERENCE_FRAME_NED);

	/**
	 * Generates a StandardMeasurementModel that relates a 3x1 attitude measurement (either RPY or
	 * tilts, depending on measurement provided) to a state vector with NED tilt error states.
	 *
	 * @param measurement Measurement of type `MeasurementAttitude3D` or `filtering::PairedPva`. The
	 * logic for what type of model is returned is as follows: If `measurement` is a plain
	 * `MeasurementAttitude3D`, a direct (identity relationship) model is generated assuming that \p
	 * gen_x_and_p_func will return a whole-valued state vector (not an error state). In other
	 * words, the first (or only) StateBlock label provided to the constructor must be the label to
	 * a whole valued state representation (usually a VirtualStateBlock). When `measurement` is a
	 * `filtering::PairedPva`, a direct (identity relationship) model is generated assuming that \p
	 * gen_x_and_p_func will return an error state vector. In other words, the first (or only)
	 * StateBlock label provided to the constructor must be the label to an error state
	 * representation (usually some variety of a Pinson15NedBlock). The assumed position of the
	 * attitude states is determined by the size of the state vector generated by concatenating all
	 * states in `state_block_labels` in order, as returned by \p gen_x_and_p_func. If \p
	 * gen_x_and_p_func returns only 3 states, these are assumed to be attitude states; if between 4
	 * and 8 states, the attitude states are assumed to be in the last 3 positions; if 9 or more
	 * states are returned, the RPY (or tilt) states are assumed to be in positions[6, 7, 8].
	 * Unsupported data types for \p measurement or a state vector of fewer than 3 states will
	 * result in a `nullptr` model and either a warning or error, depending on the setting of the
	 * global error mode (accessible with navtk::get_global_error_mode()).
	 *
	 * @param gen_x_and_p_func A function that will generate `xhat` (a Vector of estimated states,
	 * constructed from state blocks referenced by `state_block_labels`) and `P` (covariance Matrix
	 * for `xhat`) when called.
	 *
	 * @return A constructed StandardMeasurementModel if \p measurement is a `filtering::PairedPva`
	 * or `MeasurementAttitude3D`, and at least 3 states are returned by \p \p gen_x_and_p_func.
	 * Otherwise, will return `nullptr` and a warning is generated.
	 *
	 * @throw std::runtime_error If the global error mode is ErrorMode::DIE and any of the nullptr
	 *  return conditions are met.
	 */
	std::shared_ptr<StandardMeasurementModel> generate_model(
	    std::shared_ptr<aspn_xtensor::AspnBase> measurement,
	    GenXhatPFunction gen_x_and_p_func) override;

	/**
	 * Create a copy of the MeasurementProcessor with the same properties.
	 *
	 * @return A shared pointer to a copy of the MeasurementProcessor.
	 */
	not_null<std::shared_ptr<MeasurementProcessor<>>> clone() override;

private:
	const AspnMeasurementAttitude3DReferenceFrame expected_frame;
};


}  // namespace filtering
}  // namespace navtk
