name: Build wheels

on:
  [push, pull_request]

jobs:

  windows:
    name: windows | AMD64 | ${{ matrix.python }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python: [cp310-*, cp311-*, cp312-*, cp313-*, cp314-*]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/test/python --ignore={project}/test/python/error_mode_test.py"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
