name: Build wheels

on:
  [push, pull_request]

jobs:

  windows:
    name: ${{ matrix.os }} | ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [cp310-*, cp311-*, cp312-*, cp313-*, cp314-*]
        os: [windows-latest, windows-11-arm]
        exclude:
          - os: windows-11-arm
            python: cp310-*

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_ARCHS: ${{ matrix.os == 'windows-latest' && 'AMD64' || 'ARM64' }}
          CIBW_BUILD: ${{ matrix.python }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/test/python --ignore={project}/test/python/error_mode_test.py"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
